[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GITpedia"
authors = [{name = "Swastik Sharma", email = "swastkk@gmail.com"}]
dynamic = ["0.0.1", "All about Git/Github"]
